FROM python:3.11-slim


ENV HTTP_PROXY=http://host.docker.internal:10808
ENV HTTPS_PROXY=http://host.docker.internal:10808
ENV NO_PROXY=localhost,127.0.0.1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]